Repository chingu-voyage4/Geckos-Team-10, pull requests merged in 2018-03, with the labels that each got.

#6 install create-react-app
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/registerServiceWorker.js
Labels: in progress

#15 Feature initial pr #4 yordan
  src/App.js
Labels: in progress

#13 updated README
  README.md
Labels: docs, needs review

#16 added name as part of initial PR
  src/App.js
Labels: needs review

#22 delete boilerplate CRA and set up app/ directory
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/app/index.js
  src/logo.svg
Labels: needs review

#23 Created hero section #19 & Added color palettes and fonts #20
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/app/components/SlideHeader/.sass-cache/13aefd1964a30b9e9dadfc619f1c624e368d25a0/carousel.scssc
  src/app/components/SlideHeader/SlideHeader.js
  src/app/components/SlideHeader/carousel.css
  src/app/components/SlideHeader/carousel.css.map
  src/app/components/SlideHeader/carousel.scss
  src/app/images/grill.jpg
  src/app/images/grill2.jpg
  src/app/images/grill3.jpg
  src/app/index.js
  src/index.css
Labels: needs review

#25 Fix boilerplate
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/app/index.js
Labels: in progress

#24 Footer
  public/favicon.ico
  public/index.html
  src/App.js
  src/app/components/Footer/Footer.css
  src/app/components/Footer/Footer.js
  src/index.css
Labels: in progress

#28 Feature navbar #18
  package-lock.json
  package.json
  src/app/components/Navbar/Navbar.js
  src/app/components/Navbar/styles.css
  src/index.css
Labels: in progress

#29 Docs
  README.md
Labels: in progress

#37 hello world, how are you?
  src/app/index.js
Labels: needs review

#39 hello world, again?
  src/app/index.js
Labels: needs review

#41 goodbye world. yay
  src/app/index.js
Labels: needs review

#43 added random text to index.js to test
  src/app/index.js
Labels: needs review

#45 wohoo
  package.json
  src/app/index.js
Labels: needs review

#30 Resolved issues 26 and 27
  src/App.js
  src/app/components/Footer/Footer.js
Labels: needs review

#46 add pages directory and landing page
  src/app/pages/LandingPage.js
Labels: needs review

#47 add layouts directory & PrimaryLayout
  src/app/layouts/PrimaryLayout.js
Labels: needs review

#52 32 feat react router
  package-lock.json
  package.json
  src/app/components/Navbar/Navbar.js
Labels: needs review

#56 55 feat add slide header to LP
  src/app/pages/LandingPage.js
Labels: needs review

#57 add temp h1 to sign up page
  src/app/pages/SignUp.js
Labels: needs review

#58 add h1 to Book a grill page
  src/app/pages/BookGrill.js
Labels: needs review

#59 add h1 to pricing page
  src/app/pages/Pricing.js
Labels: needs review

#60 add h1 to how to grill page
  src/app/pages/HowToGrill.js
Labels: needs review

#61 53 feat add routes to primary layout
  src/app/layouts/PrimaryLayout.js
Labels: needs review

#63 54 feat browser router
  src/app/index.js
Labels: needs review

#65 fixed issue #62
  src/app/components/Footer/Footer.css
  src/app/components/Footer/Footer.js
Labels: needs review

#68 67 feat card
  src/app/components/Card/Card.js
Labels: needs review

#69 66 feat hiworks section
  src/app/components/HowItWorks/HowItWorks.js
  src/app/components/HowItWorks/styles.css
  src/app/images/user.svg
Labels: needs review

#75 73 feat imgs hiw
  src/app/components/HowItWorks/HowItWorks.js
  src/app/components/HowItWorks/styles.css
  src/app/images/agenda.svg
  src/app/images/barbecue.svg
  src/app/images/screen.svg
  src/app/images/user.svg
Labels: needs review

#76 74 style media query
  src/app/components/HowItWorks/styles.css
Labels: needs review

#79 77 style colors
  src/app/components/HowItWorks/styles.css
Labels: needs review

#80 position relative to .nav
  src/app/components/Navbar/styles.css
Labels: needs review

#82 81 add link to <HowItWorks />
  src/app/components/HowItWorks/HowItWorks.js
  src/app/components/HowItWorks/styles.css
Labels: needs review

#84 83 base style <a>
  src/app/components/HowItWorks/styles.css
  src/app/components/Navbar/styles.css
  src/index.css
Labels: needs review

#85 change card h3 font in <HowItWorks />
  src/app/components/HowItWorks/styles.css
Labels: needs review

#89 change div to main tag in pages/
  src/app/pages/BookGrill.js
  src/app/pages/HowToGrill.js
  src/app/pages/LandingPage.js
  src/app/pages/Pricing.js
  src/app/pages/SignUp.js
Labels: needs review

#86 Component: What is GrillBer
  src/app/components/SlideHeader/carousel.css
  src/app/components/WhatIsGrillber/.sass-cache/d8154903780014b54583ddcef8602e15c9ccdcfa/styles.scssc
  src/app/components/WhatIsGrillber/WhatIs.js
  src/app/components/WhatIsGrillber/styles.css
  src/app/components/WhatIsGrillber/styles.css.map
  src/app/components/WhatIsGrillber/styles.scss
  src/app/images/lists.svg
  src/app/images/steak-grill.gif
Labels: needs review

#91 adds prettier, husky, lint-staged for precommit hook
  package-lock.json
  package.json
  src/App.js
  src/app/components/Card/Card.js
  src/app/components/Footer/Footer.css
  src/app/components/Footer/Footer.js
  src/app/components/HowItWorks/HowItWorks.js
  src/app/components/HowItWorks/styles.css
  src/app/components/Navbar/Navbar.js
  src/app/components/SlideHeader/SlideHeader.js
  src/app/components/SlideHeader/carousel.css
  src/app/components/SlideHeader/carousel.scss
  src/app/components/WhatIsGrillber/WhatIs.js
  src/app/components/WhatIsGrillber/styles.css
  src/app/components/WhatIsGrillber/styles.scss
  src/app/index.js
  src/app/layouts/PrimaryLayout.js
  src/app/pages/BookGrill.js
  src/app/pages/HowToGrill.js
  src/app/pages/LandingPage.js
  src/app/pages/Pricing.js
  src/app/pages/SignUp.js
  src/index.css
  src/index.js
Labels: needs review

#93 changes h2 to h1 in header HowItWorks
  src/app/components/HowItWorks/HowItWorks.js
  src/app/components/HowItWorks/styles.css
Labels: needs review

#87 changed footer position from absolute to fixed
  src/app/components/Footer/Footer.js
Labels: needs review

#94 Fixed bug #72 and centered overlay
  src/app/components/SlideHeader/.sass-cache/b044c20ee1beb43311810e15236201263cfa2c95/carousel.scssc
  src/app/components/SlideHeader/carousel.css
  src/app/components/SlideHeader/carousel.css.map
  src/app/components/SlideHeader/carousel.scss
  src/index.css
Labels: needs review

#100 64 feature reviews
  src/app/components/Reviews/Reviews.css
  src/app/components/Reviews/Reviews.js
Labels: needs review

#102 fixed issues with slider images not fitting the window
  src/app/components/SlideHeader/carousel.css
  src/app/components/SlideHeader/carousel.scss
Labels: needs review

#103 add .cta-join to separate file in styles/, delete in local css
  src/app/components/HowItWorks/styles.css
  src/app/styles/cta-buttons.css
Labels: needs review

#105 104 feat import landing
  src/app/pages/LandingPage.js
Labels: needs review

#110 add padding bottom to hiw-section
  src/app/components/HowItWorks/styles.css
Labels: needs review

#112 108-Fixed font and added media queries
  src/app/components/SlideHeader/.sass-cache/b044c20ee1beb43311810e15236201263cfa2c95/carousel.scssc
  src/app/components/SlideHeader/SlideHeader.js
  src/app/components/SlideHeader/carousel.css
  src/app/components/SlideHeader/carousel.css.map
  src/app/components/SlideHeader/carousel.scss
Labels: needs review

#113 109 reviews height
  src/app/components/Reviews/Reviews.css
  src/app/components/Reviews/Reviews.js
Labels: needs review

#115 114 add opaque bg slider
  src/app/components/SlideHeader/carousel.css
Labels: needs review

#116 changed slider button to 'join'
  src/app/components/SlideHeader/SlideHeader.js
  src/app/components/SlideHeader/carousel.css
Labels: needs review

#122 change brand to Grillber in Navbar
  src/app/components/Navbar/Navbar.js
Labels: needs review

#127 118 style opacity join
  src/app/styles/cta-buttons.css
Labels: needs review

#124 changed h2 font weight to normal
  src/app/components/SubHeader/styles.css
Labels: needs review

#128 media queries for font size ul
  src/app/components/WhatIsGrillber/styles.css
  src/app/components/WhatIsGrillber/styles.scss
Labels: needs review

#131 #126 features creating h2
  src/app/pages/HowToGrill.js
Labels: needs review

#134 133 feat add express server
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/app/components/Card/Card.js
  client/src/app/components/Footer/Footer.css
  client/src/app/components/Footer/Footer.js
  client/src/app/components/HowItWorks/HowItWorks.js
  client/src/app/components/HowItWorks/styles.css
  client/src/app/components/Navbar/Navbar.js
  client/src/app/components/Navbar/styles.css
  client/src/app/components/Reviews/Reviews.css
  client/src/app/components/Reviews/Reviews.js
  client/src/app/components/SlideHeader/.sass-cache/13aefd1964a30b9e9dadfc619f1c624e368d25a0/carousel.scssc
  client/src/app/components/SlideHeader/.sass-cache/b044c20ee1beb43311810e15236201263cfa2c95/carousel.scssc
  client/src/app/components/SlideHeader/SlideHeader.js
  client/src/app/components/SlideHeader/carousel.css
  client/src/app/components/SlideHeader/carousel.css.map
  client/src/app/components/SlideHeader/carousel.scss
  client/src/app/components/SubHeader/SubHeader.js
  client/src/app/components/SubHeader/styles.css
  client/src/app/components/WhatIsGrillber/.sass-cache/d8154903780014b54583ddcef8602e15c9ccdcfa/styles.scssc
  client/src/app/components/WhatIsGrillber/WhatIs.js
  client/src/app/components/WhatIsGrillber/styles.css
  client/src/app/components/WhatIsGrillber/styles.css.map
  client/src/app/components/WhatIsGrillber/styles.scss
  client/src/app/images/agenda.svg
  client/src/app/images/barbecue.svg
  client/src/app/images/grill.jpg
  client/src/app/images/grill2.jpg
  client/src/app/images/grill3.jpg
  client/src/app/images/lists.svg
  client/src/app/images/screen.svg
  client/src/app/images/steak-grill.gif
  client/src/app/index.js
  client/src/app/layouts/PrimaryLayout.js
  client/src/app/pages/BookGrill.js
  client/src/app/pages/HowToGrill.js
  client/src/app/pages/LandingPage.js
  client/src/app/pages/Pricing.js
  client/src/app/pages/SignUp.js
  client/src/app/styles/cta-buttons.css
  client/src/index.css
  client/src/index.js
  client/src/registerServiceWorker.js
  package-lock.json
  package.json
  server.js
  src/app/pages/Pricing.js
  start-client.js
Labels: needs review

#138 137 style card default
  client/src/app/components/Card/Card.js
  client/src/app/components/Card/styles.css
  client/src/app/components/HowItWorks/HowItWorks.js
  client/src/app/components/HowItWorks/styles.css
Labels: needs review

#136 add express server & use cross-env to change port 4000
  client/package-lock.json
  client/package.json
Labels: needs review

#144 File Restructure #143
  client/src/app/layouts/PrimaryLayout.js
  client/src/app/pages/HowToGrill/HowToGrill.css
  client/src/app/pages/HowToGrill/HowToGrill.js
Labels: needs review

#145 add server babel config
  .babelrc
  client/package.json
  client/src/app/pages/Pricing.js
  package-lock.json
  package.json
  server.js
Labels: needs review

#147 add key property to elements in Footer
  client/src/app/components/Footer/Footer.js
Labels: needs review

#148 Fixed position of the button
  client/src/app/components/Navbar/styles.css
Labels: needs review

#150 add input componet
  client/src/app/components/Input/Input.js
  client/src/app/components/Input/styles.css
Labels: needs review

#152 Form to sign up page.
  client/src/app/pages/SignUp.js
  client/src/app/styles/cta-buttons.css
Labels: needs review

#156 added grillber rules component
  client/src/app/components/Card/styles.css
  client/src/app/components/GrillberRules/GrillberRules.js
  client/src/app/components/GrillberRules/styles.css
  client/src/app/images/biohazard.svg
  client/src/app/images/checked.svg
  client/src/app/images/error.svg
  client/src/app/images/fire.svg
  client/src/app/images/meat.svg
  client/src/app/images/spatula.svg
  client/src/app/pages/HowToGrill/HowToGrill.js
  src/app/components/GrillberRules/GrillberRules.js
  src/app/components/GrillberRules/styles.css
Labels: needs review

#157 #153 SignUp logo added
  client/src/app/images/signup_logo.svg
  client/src/app/pages/SignUp.js
Labels: needs review

#163 162 delete src
  src/app/components/GrillberRules/GrillberRules.js
  src/app/components/GrillberRules/styles.css
Labels: needs review

#165 164 feat mongoose
  .gitignore
  package-lock.json
  package.json
  server.js
  server/models/User.js
  server/server.js
  server/start-client.js
Labels: needs review

#167 166 feat mocha mongo
  .gitignore
  package-lock.json
  package.json
  test/connection.js
  test/finding_db.js
  test/saving_db.js
Labels: needs review

#169 168 feat apollo server
  .babelrc
  package-lock.json
  package.json
  server/graphql/Resolvers/resolvers.js
  server/graphql/schema.js
  server/graphql/typeDefs/typeDefs.js
  server/server.js
Labels: needs review

#173 171 feat grill model
  server/models/Grill.js
  server/server.js
Labels: needs review

#176 adds grill schema graphql
  server/graphql/typeDefs/typeDefs.js
Labels: needs review

#177 add grill graphql resolver
  server/graphql/Resolvers/resolvers.js
Labels: needs review

#178 closes issue 174
  client/src/app/pages/Pricing.js
  server/server.js
Labels: needs review

#181 179. resolver by grill(name)
  server/graphql/Resolvers/resolvers.js
  server/graphql/typeDefs/typeDefs.js
  server/server.js
Labels: needs review

#184 170 feat mutation create user
  server/graphql/Resolvers/resolvers.js
  server/graphql/typeDefs/typeDefs.js
Labels: needs review

#182 154-feat-spinnerLoader
  client/src/app/components/Loader/Loader.css
  client/src/app/components/Loader/Loader.js
  client/src/app/pages/Pricing.js
Labels: needs review

#186 185 feat faq pricing
  client/src/app/components/FAQ/Faq.js
  client/src/app/components/FAQ/styles.css
Labels: needs review

#187 183 resolver to find user by _id
  server/graphql/Resolvers/resolvers.js
  server/graphql/typeDefs/typeDefs.js
Labels: needs review

#192 add apollo client and provider to app component
  client/src/app/index.js
Labels: needs review

#194 uninstall react apollo on server
  package-lock.json
  package.json
Labels: needs review
